@startuml syouhin_tuika

actor "会員" as act
boundary "商品\n詳細画面" as shb
boundary "ブラウザ" as brz
control "カート追加\nビュー" as cac
entity "商品" as product
entity "カート" as cart
boundary "商品\n一覧画面" as sib
control "追加完了\nビュー" as shkc

act -> shb: 追加ボタンをクリックする

shb -> cac: POST（商品の主キー）
cac -> product: 商品の在庫情報を取得する
cac <-- product
alt 在庫なし
    shb <- cac: エラーメッセージを表示する
end
cac -> cart: カートに追加する
cac -> shkc: リダイレクト
sib <- shkc: 表示する        

@enduml