@startuml syouhin_tuika

actor "会員" as act
boundary "商品\n詳細画面" as shb
boundary "ブラウザ" as brz
control "カート追加\nコントローラー" as shc
entity "商品\nDAO" as product
control "追加完了\nコントローラー" as shkc
boundary "商品\n一覧画面" as sib
boundary "カート追加\n完了画面" as shkb

shc <- brz: GET
shc -> product: 商品情報を取得する
shc <-- product
shb <- shc: 表示する
act -> shb: 追加ボタンをクリックする

alt 在庫がない
    
    shb -> shb: ツールチップを表示する
else
    shb -> shc: POST（商品情報）

    else
        shc -> product: カートに追加する
        shc -> sib: アラートを表示する
        shc -> shc: リダイレクト
        shb <- shc: 表示する
        shkc -> shkb: 追加完了
end
@enduml