@startuml cartdelete

actor "会員" as act
boundary "カート\n画面" as cartv
boundary "ブラウザ" as brz
control "カート商品削除\nビュー" as delete
entity "カート" as cart
control "カート一覧\nビュー" as shkc


act -> cartv:削除ボタンを\nクリックする
cartv -> cartv:「商品をカートから\n削除しますか？」\nとアラートを表示 
act -> cartv:はいをクリックする
cartv -> delete:POST()
    delete -> cart:商品を削除する
    delete -> shkc:リダイレクト
    cartv <- shkc:カート画面と削除完了メッセージを表示

@enduml
