@startuml cart_tuika

actor "会員ユーザー" as act
boundary "カート画面" as cart
boundary "ブラウザ" as brz
control "数量変更ビュー" as shv
entity "在庫データ" as stockdata
entity "カート情報" as cartinfo
boundary "数量変更\n完了ビュー" as shkv

act -> cart:カートの商品の\n数量を変更する
cart -> shv: GET()
shv -> stockdata: 在庫データを取得
shv <-- stockdata:

alt 在庫あり
    shv -> cartinfo: 変更した内容を更新する
    shv -> shkv: リダイレクト
    cart <- shkv: 変更後のカート内容を表示する

else 在庫なし
    shv -> cart: エラーメッセージを表示する
end

@enduml