'サインアップする
@startuml singnup
' ①縦軸の並び順を決める
actor "会員ユーザー" as act
boundary "ログイン画面" as log
' コントローラーに初回アクセスするもの
boundary "ブラウザ" as brz
' コントローラーまたはビューの名称を決める
control "ログインコントローラー" as ktc
' DAOまたはモデルとなる
entity "会員アカウントDAO" as kaccount
boundary "ログイン完了" as kkb

' ②手順を時系列に記述する
brz -> ktc: GET
ktc -> kaccount: すべてのアカウント情報を取得する
log  <- ktc: 表示する

act -> log: 会員情報を入力し\nログインボタンを\nクリック

alt 項目未入力がある
    ' HTMLで行うことなので自己向き矢印にしている
    log -> log: ツールチップを表示する

    ' サーバーに送信する
    ' どんなデータを送信するのかを記述
    log -> ktc: POST (会員情報)
    else メールアドレスが一致しない
        log <- ktc: メッセージを表示する
    else パスワードが一致しない
        log <- ktc: メッセージを表示する    
    else
        ktc -> kaccount: メールアドレスで検索する
        ktc <-- kaccount
        alt メールアドレスが登録済み
            log <- ktc: メッセージを表示する
        else
            ktc -> kaccount: ログインする
            ktc -> kaccount: ログインする

            ktc -> kkc: リダイレクト
            kkb <- kkc: 表示する
        end
    end
end


@enduml