@startuml registration
actor "非会員ユーザー" as act
boundary "会員登録" as reg
control "会員登録JS" as regjs
boundary "ブラウザ" as brz
control "会員登録\nコントローラー" as regc
entity "アカウント" as account
boundary "登録完了" as regk
control "登録完了\nコントローラー" as regc2


reg -> brz: 会員登録画面表示
brz -> regjs: 登録情報入力
regjs -> regc: サインアップリクエスト送信

alt メールアドレスが登録済みの場合
    regc -> account: メールアドレス確認
    account --> regc: 利用できません
    regc -> brz: このメールアドレスは利用できませんと表示
else パスワード条件未満の場合
    regc -> regjs: パスワード条件を確認
    regjs -> brz: パスワードは半角英大文字小文字数字を含む8文字以上にしてくださいと表示
else パスワード不一致の場合
    regc -> regjs: パスワード確認
    regjs -> brz: パスワードが一致しませんと表示
else 正常登録の場合
    regc -> account: アカウント作成
    account --> regc: 登録成功
    regc -> regc2: 登録完了通知
    regc2 -> regk: 登録完了画面表示
    regk --> act: 登録完了通知
end

@enduml
