@startuml kaiin_touroku
actor "店長" as manager
boundary "従業員登録画面" as reg
control "従業員登録\nコントローラー" as regc
entity "従業員アカウント" as emp_account
boundary "会員登録完了画面" as regk
boundary "アラート" as alert
boundary "ツールチップ" as tooltip
control "店舗取得" as shop_get
entity "店舗" as shop

manager -> reg: 会員情報を入力
manager -> reg: サインアップボタンをクリック

alt 未入力のものがある場合
    regc -> tooltip: ツールチップを表示する
else パスワード条件未満の場合
    regc -> alert: パスワードは8文字以上、英大文字・小文字・数字を含める必要がありますと表示
else メールアドレスが登録済みの場合
    regc -> emp_account: メールアドレス確認
    emp_account --> regc: メールアドレスが既に登録済み
    regc -> alert: エラーメッセージを表示する
else 正常な入力の場合
    regc -> emp_account: メールアドレスとパスワードで従業員アカウント登録
    emp_account --> regc: 登録成功
    regc -> regk: 会員登録完了画面を表示
    regk --> manager: アカウント登録完了
end

alt すべての店舗を取得する場合
    regc -> shop_get: 店舗リスト取得
    shop_get --> shop: すべての店舗を取得する
    shop -> reg: 店舗情報を表示
end
@enduml
