@startuml syouhin_touroku
actor "従業員" as act
boundary "商品登録画面" as stb
boundary "ブラウザ" as brz

control "商品登録コントローラー" as stc

entity "商品DAO" as product

boundary "商品登録完了" as skb
control "商品登録完了コントローラー" as skc

brz -> stc: GET

stb <- stc: 表示する

act -> stb: 商品情報を入力する

alt 項目に未入力がある
    
    stb -> stb: ツールチップを表示する
else
    stb -> stc: POST（商品情報）

    else
        stc -> product: 登録する

        stc -> skc: リダイレクト
        skb <- skc: 表示する
end
@enduml