@startuml syouhin_henkou
actor "従業員" as act
boundary "商品情報変更画面" as shb
boundary "ブラウザ" as brz
control "商品変更ビュー" as shc
entity "商品" as product
boundary "商品変更完了画面" as shkb
control "商品変更完了ビュー" as shkc

' 商品の主キーを()の中に入れる
shc <- brz: GET()
shc -> product: 商品情報を取得
shc <-- product:
shb <- shc: 表示する
act -> shb: 商品情報を入力する

alt 未入力の項目がある
    
    shb -> shb: ツールチップを表示する
else
    shb -> shc: POST（商品情報）

    shc -> product: 変更する
    shc -> shkc: リダイレクト 
    shkc -> shkb: 表示する
end
@enduml