@startuml syouhin_henkou
actor "従業員" as act
boundary "商品情報変更画面" as shb
boundary "ブラウザ" as brz
control "商品変更コントローラー" as shc
entity "商品DAO" as product
control "商品変更完了コントローラー" as shkc
boundary "商品一覧画面" as sib
boundary "商品変更完了画面" as shkb

shc <- brz: GET

shb <- shc: 表示する

act -> shb: 商品情報を入力する

alt 未入力の項目がある
    
    shb -> shb: ツールチップを表示する
else
    shb -> shc: POST（商品情報）

    else
        shc -> product: 変更する
        shc -> sib: アラートを表示する
        shc -> shc: リダイレクト
        shb <- shc: 表示する
        shkc -> shkb: 変更完了
end
@enduml