@startuml order
actor "会員ユーザー" as act

boundary "注文確定画面" as okb
boundary "ブラウザ" as brz
control "注文確定\nビュー" as okc
entity "注文" as order
boundary "決済完了画面" as okkb
control "決済完了\nビュー" as kkc

brz -> okc: GET

okb <- okc:表示する

act -> okb:決済方法を選択し\n注文を確定する

act -> okb :カード情報を入力する

act -> okb :振込情報を入力する

act -> okb :振込情報を入力する


alt 項目に未入力がある
    okb -> okb:ツールチップを表示する
end

okb -> okc:POST()

okc -> order:注文情報を追加
okc -> kkc:リダイレクト


kkc -> okkb:表示する
@enduml