' サインアップする
@startuml update
' ①縦軸の並び順を決める
actor "従業員" as act
boundary "注文一覧画面" as oeb
' コントローラーに初回アクセスするもの
boundary "ブラウザ" as brz
' コントローラーまたはビューの名称を決める
control "注文編集コントローラー" as oec
' DAOまたはモデルとなる

entity "商品DAO" as pdt
entity "注文DAO" as order

boundary "注文編集完了" as oekb
control "注文編集完了コントローラー" as oekc

brz -> oec: GET

oeb <- oec:表示する

act -> oeb:注文状況を選択し\n完了ボタンを\nクリックする

oec <- pdt:すべての注文を取得する
oec <- order:すべての注文を取得する

oec -> order: 登録する

oekc -> oekb:表示する

@enduml