@startuml list
' ①縦軸の並び順を決める
actor "従業員" as act
boundary "注文一覧画面" as oeb
' コントローラーに初回アクセスするもの
boundary "ブラウザ" as brz
' コントローラーまたはビューの名称を決める
control "注文一覧ビュー" as oec
' DAOまたはモデルとなる
' entity "アカウント" as account
' entity "商品" as pdt
entity "注文" as order

brz -> oec: GET

oeb <- oec:表示する

act -> oeb:注文一覧を\n表示させたい日付の\n日付ボタンをクリックする
oeb ->oec:GET(日付)
' oec -> account:すべての注文を取得する
' account --> oec
' oec -> pdt:すべての注文を取得する
' pdt --> oec
oec -> order:指定された日付の注文を取得する
order --> oec

alt 指定した日付に注文がない
    oeb <- oec:メッセージを表示する
else 
    oeb <- oec:表示する
end

@enduml