' 返品処理をする
@startuml return
' ①縦軸の並び順を決める
actor "従業員" as act
boundary "注文返品画面" as orb
' コントローラーに初回アクセスするもの
boundary "ブラウザ" as brz
' コントローラーまたはビューの名称を決める
control "注文返品コントローラー" as orc
' DAOまたはモデルとなる
entity "商品DAO" as pdt
entity "注文DAO" as order

boundary "注文返品完了" as orkb
control "注文返品完了コントローラー" as orkc

brz -> orc: GET

orb <- orc:表示する

act -> orb:返品手続きをする

orc <- pdt:すべての注文を取得する
orc <- order:すべての注文を取得する

alt 項目に未入力がある
    orb <- orc:アラートを表示する
end

orc -> orkc: リダイレクト
orkb <- orkc:表示する

@enduml

