@startuml return
' ①縦軸の並び順を決める
actor "会員" as act
boundary "注文\n返品画面" as orb
' コントローラーに初回アクセスするもの
boundary "ブラウザ" as brz
' コントローラーまたはビューの名称を決める
control "注文返品\nビュー" as orc
' DAOまたはモデルとなる
entity "商品" as pdt
entity "注文" as order
boundary "返品\n完了画面" as orkb
control "注文返品完了\nビュー" as orkc

brz -> orc: GET
orc -> order:注文を取得する
orc <-- order
orc -> pdt:商品を取得する
orc <-- pdt
orb <- orc:表示する
act -> orb:返品手続きをする


alt 項目に未入力がある
    orb <- orc:アラートを表示する
end

orc -> order: 注文を変更する
orc -> orkc: リダイレクト
orkb <- orkc:表示する

@enduml

