@startuml KR
 
actor "会員" as user
boundary "お知らせ\n画面" as Posts
boundary "ブラウザ" as brz
control "お知らせ\ビュー" as Postv
entity "お知らせ" as Post
 
brz -> Postv: GET(お知らせ)
Postv -> Post: お知らせを取得
Postv <-- Post:
Posts <- Postv:お知らせを表示
 
@enduml