' @startuml KR
 
' actor "会員" as user
' boundary "お知らせ\n詳細画面" as PostDetails
' boundary "ブラウザ" as brz
' control "お知らせ\詳細ビュー" as PostDetailv
' entity "お知らせ" as Post
 
' brz -> PostDetailv: GET(お知らせ)
' PostDetailv -> Post: お知らせを取得
' PostDetailv <-- Post:
' PostDetails <- PostDetailv:お知らせ詳細を表示
 
' @enduml