@startuml KR
 
actor "会員" as user
boundary "トップ画面" as PostDetails
boundary "ブラウザ" as brz
control "トップビュー" as PostDetailv
entity "投稿" as Post
 
brz -> PostDetailv: GET(投稿)
PostDetailv -> Post: 投稿を取得
PostDetailv <-- Post:
PostDetails <- PostDetailv:トップ画面に\n投稿を表示
 
@enduml