' @startuml syouhin_touroku
' actor "会員" as user
' boundary "プロフィール編集画面" as ProfileEditb
' boundary "ブラウザ" as brz
' control "プロフィール\n編集ビュー" as ProfileEditv
' entity "アカウント" as account
' boundary "プロフィール\n編集完了画面" as Profileokb
' control "プロフィール\n編集完了ビュー" as ProfileEditc

' brz -> ProfileEditv:GET
' ProfileEditb <- ProfileEditv:表示する
' user -> ProfileEditb: プロフィール編集情報を\n入力し、完了ボタンを\nクリックする
' ProfileEditb -> ProfileEditv: POST（プロフィール）
' ProfileEditv -> account: 変更する
' ProfileEditv -> ProfileEditc: リダイレクト 
' Profileokb <- ProfileEditc: 表示する
' @enduml