@startuml money
actor "会員" as user
boundary "募金申し込み\n画面" as Moneys
boundary "ブラウザ" as brz
control "募金申し込み\nビュー" as Moneyv
boundary "募金手続き\n画面" as MoneyPs
control "募金手続き\nビュー" as MoneyPv

brz -> Moneyv:GET
Moneys <- Moneyv:表示する
user -> Moneys:「寄付する」\nボタンをクリックする
Moneys -> MoneyPv:GET
MoneyPs <- MoneyPv:表示する
@enduml