"""
Django settings for TRAVELPPROJECT project.
 
Generated by 'django-admin startproject' using Django 4.0.
 
For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/
 
For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
 
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
 
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$g9#2d6e(qmq9zq$)fsz*b$h3byoe#6dgoiicfs^4cz*bytc^6'
 
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
 
ALLOWED_HOSTS = []
# Application definition
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'travelp.apps.TravelpConfig',
    # accountsアプリを追加する
    'accounts.apps.AccountsConfig',
]
 
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
 
ROOT_URLCONF = 'TRAVELPPROJECT.urls'
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],  # テンプレートディレクトリがあればここに追加
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # プロジェクト全体のテンプレートを探すディレクトリ
            BASE_DIR / 'accounts' / 'templates',  # accountsアプリのテンプレートを探すディレクトリ
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'TRAVELPPROJECT.wsgi.application'
 
 
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
 
 
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators
 
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
 
 
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/
 
LANGUAGE_CODE = 'ja'
 
TIME_ZONE = 'Asia/Tokyo'
 
USE_I18N = True
 
USE_TZ = True
 
 
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
 
STATIC_URL = '/static/'
 
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'),]

# Userモデルの代わりにCustomUserモデルを使用する
AUTH_USER_MODEL = 'accounts.CustomUser'

 
# Userモデルの代わりにCustomUserモデルを使用する
AUTH_USER_MODEL = 'accounts.CustomUser'
 
# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.static',  # ここを追加
            ],
        },
    },
]


# mediaのURLを登録
MEDIA_URL = '/media/'
# mediaフォルダーの場所(BASE_DIR以下のmedia)を登録
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_URL = '/login'
LOGIN_REDIRECT_URL = '/'

# settings.py
STRIPE_PUBLIC_KEY = "pk_test_51QnCXI2Nxfmaq9ljdf4mDAqOqbzBCH0fkLDhKKW8ZazsgGslVdUu4RQQcmQx3vN2ym4SwrKGy0iXQQBugWQYfknZ002jZ9xV4B" # 公開キー
STRIPE_SECRET_KEY = "sk_test_51QnCXI2Nxfmaq9ljQkrII49KgKQzzd4bBDLqnReA0gd88nQm0vtuqce5EPDNHwjTIk6gcwqSThncNnhnPW67i6Tn00V88Mu5r7" # シークレットキー
 

# メールバックエンド設定（デバッグ環境ではコンソールに出力されます）
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # 開発環境用。プロダクションでは他のバックエンドを使用する

# メール送信者のアドレス
DEFAULT_FROM_EMAIL = 'webmaster@localhost'