# Generated by Django 4.0 on 2025-01-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0002_post_caption_comment_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
