# Generated by Django 4.0 on 2025-01-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0003_rename_posted_at_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, verbose_name='場所'),
        ),
    ]
