# Generated by Django 4.0 on 2025-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0007_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
