# Generated by Django 4.0 on 2025-01-28 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0008_donation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraising',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
