# Generated by Django 4.0 on 2025-02-05 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0012_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='posts',
            field=models.ManyToManyField(related_name='plans', to='travelp.Post'),
        ),
    ]
