# Generated by Django 4.0 on 2025-02-07 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0016_fundraisingproject_alter_donation_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundraising',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fundraising',
            name='raised_amount',
        ),
        migrations.RemoveField(
            model_name='fundraising',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fundraising',
            name='collected_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='post',
            name='fundraising',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelp.fundraising'),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fundraising',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
