# Generated by Django 4.0 on 2025-02-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0017_remove_fundraising_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fundraising',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=15, null=True),
        ),
    ]
