# Generated by Django 4.0 on 2025-02-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travelp', '0018_alter_post_fundraising_alter_post_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fundraising',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travelp.fundraising'),
        ),
    ]
