@startuml KD

actor "事務職員" as staff
boundary "貸出\n入力画面" as KDIns
boundary "貸出\n選択画面" as KDSelects
boundary "ブラウザ" as brz
control "貸出\nビュー" as KDv
entity "貸出\n履歴" as KDR
entity "本" as book
entity "会員" as member
boundary "貸出\n完了画面" as KDOKs
control "貸出\n完了ビュー" as KDOKv

brz -> KDv::GET
KDIns <- KDv:表示する
staff -> KDIns: 会員番号、管理番号を\n入力して次へボタン\nをクリックする
alt 会員番号または管理番号が未入力の場合
    KDIns <- KDv: ツールチップを表示する
else 
    KDIns -> KDv: GET(?)
    KDv -> member: 会員情報を取得
    KDv <-- member
    KDv -> book: 本の情報を取得
    KDv <-- book
    alt 会員が存在しない場合
        KDIns <- KDv: メッセージを表示する
    else 超過している貸出が存在する場合
        KDIns <- KDv:メッセージを表示する
    end
    KDSelects <- KDv:表示する
    alt 管理番号が存在しない場合
        KDSelects <- KDv: メッセージと管理番号\nの一覧を表示する
    else 会員の会員区分が「学生」で、図書の種別が「雑誌」の場合
        KDSelects <- KDv: メッセージと書名の一覧を表示する
    end
    staff -> KDSelects: 貸出する本を選択し、「決定」ボタンをクリックする
    KDSelects -> KDv: GET (?)
    KDv -> member: 貸出可能冊数を取得
    KDv <-- member

    alt 選択した本の冊数が貸出可能冊数を超える場合
        KDSelects <- KDv: アラートを表示する
        KDSelects <- KDv: 表示する
    else 選択した本の冊数が貸出可能冊数以下の場合
        KDSelects -> KDv: POST（?）
        KDv -> book: 貸出情報を登録する
        KDv -> member: 貸出可能冊数を更新する
        KDv -> KDOKv: リダイレクト
        KDOKs <- KDOKv: 貸出完了画面を表示する
    end

end

@enduml