@startuml HK
 
actor "事務職員" as staff
boundary "返却\n検索画面" as HKKs
boundary "返却\n確認画面" as HKChecks
boundary "ブラウザ" as brz
control "返却\n検索ビュー" as HKKv
control "返却\nビュー" as HKv
entity "貸出\n履歴" as KDR
entity "貸出\n予約" as KDY
entity "本" as book
entity "会員" as member
boundary "返却\n完了画面" as HKOKs
control "返却完了\nビュー" as HKOKv
 
brz -> HKKv:GET
HKKs <- HKKv:表示する
staff -> HKKs: 管理番号を入力\nして次へボタン\nをクリックする
alt 管理番号が未入力の場合
    HKKs -> HKKs: ツールチップを表示
else
    HKKs -> HKKv: GET(貸出履歴)
    HKKv -> KDR: 貸出履歴を取得
    HKKv <-- KDR
    alt 管理番号が存在しない場合
        HKKs -> HKKs: エラーメッセージを表示
    else 管理番号が存在する場合
        HKKs -> HKKv:GET
        HKChecks <- HKKv: 表示する
        staff -> HKChecks: 決定ボタンをクリックする
        HKChecks -> HKv: POST(ステータス)
        HKv -> member: 変更する
        HKv -> HKOKv: リダイレクト
        HKChecks -> HKOKv: GET(貸出予約)
        KDY <- HKOKv: 貸出予約を取得
        KDY --> HKOKv
        HKOKs <- HKOKv: 返却完了画面を表示
        alt 貸出予約されていた場合
            HKOKv -> HKOKs: メッセージと書名リスト\nも表示する
        end
    end
end
 
@enduml